let products =  [
  {
  img: [
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product8-582x650.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product8-1-582x650.jpg",
  ],
  productId: 0,
  productName: "SNIKSA KAHLA PLA",
  price: "118.00",
  discount: "1",
  discountPrice: "95.00",
  newProduct : "1",
  description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  review: "0",
  categories: ["Shoes", "Trapper"],
  color: ["Black", "Brown"],
  size: ["39, 40, 41, 42, 43"],
  productTags: ["black","boots","Cotton","glasses","red","shoes","Yepme"],
},
{
  img: [
  "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product10-1-582x650.jpg",
  "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product10-582x650.jpg",
],
  productId: 1,
  productName: "SIGMA KABA ZARGA",
  price: "85.00",
  discount: "0",
  discountPrice: "",
  newProduct : "1",
  description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  review: "4",
  categories: ["Accessories", "Bag"],
  color: ["Black", "Brown"],
  size: ["39, 40, 41, 42, 43"],
  //productTags: ["black","boots","Cotton","glasses","red","shoes","Yepme"],
},
{
  img: [
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product2.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product2-1-582x650.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product2-2-582x650.jpg",
  ],
      productId: 2,   
      productName: "SBIBITA KAHLA SAFRA",
      price: "254.00",
      discount: "0",
      discountPrice: "",
      newProduct : "1",
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
      review: "4",
      categories: ["Shoes", "Trapper"],
      color: ["Black", "Brown"],
      size: ["39, 40, 41, 42, 43"],
      productTags: ["black","boots","Cotton","glasses","red","shoes","Yepme"],
},
{
  img: [
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product1-582x650.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product1-1-582x650.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product1-2-582x650.jpg",
  ],
      productId: 3,
      productName: "SBIBITA ENIGMA KAHLA",
      price: "320.00",
      discount: "0",
      discountPrice: "",
      newProduct : "1",
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
      review: "5",
      categories: ["Shoes", "Trapper"],
      color: ["Black", "Brown"],
      size: ["39, 40, 41, 42, 43"],
      productTags: ["black","boots","Cotton","glasses","red","shoes","Yepme"],
},
{
  img: [
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product11-582x650.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product11-1.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product11-2-582x650.jpg",
  ],
      productId: 4,
      productName: "SBIBITA ENIGMA HAMRA",
      price: "320.00",
      discount: "0",
      discountPrice: "",
      newProduct : "1",
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
      review: "3",
      categories: ["Shoes", "Trapper"],
      color: ["Black", "Brown"],
      size: ["39, 40, 41, 42, 43"],
      productTags: ["black","boots","Cotton","glasses","red","shoes","Yepme"],
}, 
{
  img: [
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product9-582x650.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product9-1-582x650.jpg",
  ],
      productId: 5,
      productName: "SABAT JELD KWIR",
      price: "320.00",
      discount: "0",
      discountPrice: "",
      newProduct : "1",  
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
      review: "0",
      categories: ["Shoes", "Sabat"],
      color: ["Black", "Brown"],
      size: ["39, 40, 41, 42, 43"],
      productTags: ["black","boots","Cotton","glasses","red","shoes","Yepme"],
},
{
  img: [
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product7-582x650.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product7-1-582x650.jpg",
  ],
      productId: 6,
      productName: "NWADER KOHEL DORIGIN",
      price: "150.00",
      discount: "0",
      discountPrice: "",
      newProduct : "1", 
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
      review: "0",
      categories: ["Accessories"],
      color: ["Black", "Brown"],
      size: ["39, 40, 41, 42, 43"],
      productTags: ["black","boots","Cotton","glasses","red","shoes","Yepme"],
},
{
  img: [
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product12-582x650.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product12-2-582x650.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product12-1.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product12-582x650.jpg",
  ],
      productId: 7,
      productName: "CASK MARKA BAYDA",
      price: "200.00",
      discount: "0",
      discountPrice: "",
      newProduct : "1",
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
      review: "5",
      categories: ["Accessories"],
      color: ["Black", "Brown"],
      size: ["39, 40, 41, 42, 43"],
      productTags: ["black","boots","Cotton","glasses","red","shoes","Yepme"],
},
{
  img: [
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product5-582x650.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product5-582x650.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product5-1-582x650.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/revslider/shop/slide-element-2-582x650.jpg",
  ],
      productId: 8,
      productName: "BITA KABA KAHLA",
      price: "55.00",
      discount: "0",
      discountPrice: "",
      newProduct : "0",
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
      review: "5",
      categories: ["Accessories", "Bag"],
      color: ["Black", "Brown"],
      size: ["39, 40, 41, 42, 43"],
      productTags: ["black","boots","Cotton","glasses","red","shoes","Yepme"],
},
{
  img: [
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product4-582x650.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product4-582x650.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product4-1-582x650.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product4-2-582x650.jpg",
  ],
      productId: 9,
      productName: "BOOT ASFAR CHTAWI",
      price: "220.00",
      discount: "1",
      discountPrice: "190.00",
      newProduct : "0",
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
      review: "4",
      categories: ["Sabat", "Shoes"],
      color: ["Black", "Brown"],
      size: ["39, 40, 41, 42, 43"],
      productTags: ["black","boots","Cotton","glasses","red","shoes","Yepme"],
},
{
img: [
  "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product3-582x650.jpg",
  "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product3-2-582x650.jpg",
  "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product3-1-582x650.jpg",
  "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product3-582x650.jpg",
],
  productId: 10,
  productName: "BOOT JELD HOR",
  price: "320.00",
  discount: "1",
  discountPrice: "290.00",
  newProduct : "0",
  description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
  review: "3",
  categories: ["Shoes", "Trapper"],
  color: ["Black", "Brown"],
  size: ["39, 40, 41, 42, 43"],
  productTags: ["black","boots","Cotton","glasses","red","shoes","Yepme"],
},
{
  img: [
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product6-582x650.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product6-2-582x650.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product6-1-582x650.jpg",
      "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product6-582x650.jpg",
  ],
      productId: 11,
      productName: "BOSTAYTOS MARKA",
      price: "175.00",
      discount: "0",
      discountPrice: "",
      newProduct : "0",
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
      review: "0",
      categories: ["Shoes", "Trapper"],
      color: ["Black", "Brown"],
      size: ["39, 40, 41, 42, 43"],
      productTags: ["black","boots","Cotton","glasses","red","shoes","Yepme"],
}
]

let orderList = [
    {
        id: "001",
      add1: "Số 11, đường A, phường B, quận Hoàn Kiếm",
      add2: "",
      city: "Hanoi",
      company: "",
      email: "tunghoang736@gmail.com",
      firstName: "Tung",
      lastName: "Hoang",
      notes: "",
      phone: "0987675736",
      region: "Viet Nam",
      zipCode: "100000",
      orderItem: [
        {
          sl: 3,
          pItem: {
            categories: ["Shoes", "Trapper"],
            color: ["Black", "Brown"],
            description:
              "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
            discount: "0",
            discountPrice: "",
            img: [
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product2.jpg",
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product2-1-582x650.jpg",
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product2-2-582x650.jpg",
            ],
            newProduct: "1",
            price: 254,
            productId: 2,
            productName: "SBIBITA KAHLA SAFRA",
            productTags: [
              ("black", "boots", "Cotton", "glasses", "red", "shoes", "Yepme"),
            ],
            review: "4",
            size: ["39, 40, 41, 42, 43"],
          },
        },
        {
          sl: 3,
          pItem: {
            categories: ["Shoes", "Trapper"],
            color: ["Black", "Brown"],
            description:
              "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
            discount: "0",
            discountPrice: "",
            img: [
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product1-582x650.jpg",
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product1-1-582x650.jpg",
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product1-2-582x650.jpg",
            ],
            newProduct: "1",
            price: 320,
            productId: 3,
            productName: "SBIBITA ENIGMA KAHLA",
            productTags: [
              "black",
              "boots",
              "Cotton",
              "glasses",
              "red",
              "shoes",
              "Yepme",
            ],
            review: "5",
            size: ["39, 40, 41, 42, 43"],
          },
        },
      ],
    },
    {
        id:"002",
      add1: "Số 3, đường Aemond, quận Aegon",
      add2: "Số 1103, Chung cư ABC, quận Aegon",
      city: "Ho Chi Minh City",
      company: "Klose",
      email: "hohung481@gmail.com",
      firstName: "Hung",
      lastName: "Ho",
      phone: "0987657481",
      region: "Viet Nam",
      zipCode: "100000",
      notes: "",
      orderItem: [
        {
          pItem: {
            categories: [("Shoes", "Trapper")],
            color: [("Black", "Brown")],
            description:
              "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
            discount: "1",
            discountPrice: 95,
            img: [
              ("https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product8-582x650.jpg",
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product8-1-582x650.jpg"),
            ],
            newProduct: "1",
            price: 118,
            productId: 0,
            productName: "SNIKSA KAHLA PLA",
            productTags: [
              ("black", "boots", "Cotton", "glasses", "red", "shoes", "Yepme"),
            ],
            review: "0",
            size: ["39, 40, 41, 42, 43"],
          },
          sl: 1,
        },
  
        {
          pItem: {
            categories: [("Shoes", "Trapper")],
            color: [("Black", "Brown")],
            description:
              "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
            discount: "0",
            discountPrice: "",
            img: [
              ("https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product1-582x650.jpg",
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product1-1-582x650.jpg",
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product1-2-582x650.jpg"),
            ],
            newProduct: "1",
            price: 320,
            productId: 3,
            productName: "SBIBITA ENIGMA KAHLA",
            productTags: [
              ("black", "boots", "Cotton", "glasses", "red", "shoes", "Yepme"),
            ],
            review: "5",
            size: ["39, 40, 41, 42, 43"],
          },
          sl: 1,
        },
  
        {
          pItem: {
            categories: [("Shoes", "Trapper")],
            color: [("Black", "Brown")],
            description:
              "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
            discount: "0",
            discountPrice: "",
            img: [
              ("https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product2.jpg",
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product2-1-582x650.jpg",
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product2-2-582x650.jpg"),
            ],
            newProduct: "1",
            price: 254,
            productId: 2,
            productName: "SBIBITA KAHLA SAFRA",
            productTags: [
              ("black", "boots", "Cotton", "glasses", "red", "shoes", "Yepme"),
            ],
            review: "4",
            size: ["39, 40, 41, 42, 43"],
          },
          sl: 1,
        },
      ],
    },
    {
        id: "003",
      add1: "No. 211B, Becker street ",
      add2: "",
      city: "London",
      company: "Conan Doyle",
      email: "holmes.pro.no.1@gmail.com",
      firstName: "Holmes",
      lastName: "Sherlock",
      phone: "0129381231",
      region: "United Kingdom",
      zipCode: "58000",
      notes: "",
      orderItem: [
        {
          pItem: {
            categories: [("Accessories", "Bag")],
            color: [("Black", "Brown")],
            description:
              "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
            discount: "0",
            discountPrice: "",
            img: [
              ("https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product10-1-582x650.jpg",
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product10-582x650.jpg"),
            ],
            newProduct: "1",
            price: 85,
            productId: 1,
            productName: "SIGMA KABA ZARGA",
            review: "4",
            size: ["39, 40, 41, 42, 43"],
          },
  
          sl: 2,
        },
        {
          pItem: {
            categories: [("Shoes", "Trapper")],
            color: [("Black", "Brown")],
            description:
              "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
            discount: "0",
            discountPrice: "",
            img: [
              ("https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product1-582x650.jpg",
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product1-1-582x650.jpg",
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product1-2-582x650.jpg"),
            ],
            newProduct: "1",
            price: 320,
            productId: 3,
            productName: "SBIBITA ENIGMA KAHLA",
            productTags: [
              ("black", "boots", "Cotton", "glasses", "red", "shoes", "Yepme"),
            ],
            review: "5",
            size: ["39, 40, 41, 42, 43"],
          },
          sl: 1,
        },
      ],
    },
    {
        id: "004",
      add1: "001, Acer street, Asus ward",
      add2: "",
      city: "Gigabyte",
      company: "Prison Studio",
      email: "jonathan.the.prisoner001@gmail.com",
      firstName: "Majors",
      lastName: "Jonathan",
      phone: "098461641",
      region: "United States",
      zipCode: "150000",
      notes: "boom",
      orderItem: [
        {
          pItem: {
            categories: ["Shoes", "Trapper"],
            color: ["Black", "Brown"],
            description:
              "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
            discount: "1",
            discountPrice: 95,
            img: [
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product8-582x650.jpg",
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product8-1-582x650.jpg",
            ],
            newProduct: "1",
            price: 118,
            productId: 0,
            productName: "SNIKSA KAHLA PLA",
            productTags: [
              "black",
              "boots",
              "Cotton",
              "glasses",
              "red",
              "shoes",
              "Yepme",
            ],
            review: "0",
            size: ["39, 40, 41, 42, 43"],
          },
          sl: 1,
        },
        {
          pItem: {
            categories: ["Shoes", "Trapper"],
            color: ["Black", "Brown"],
            description:
              "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
            discount: "0",
            discountPrice: "",
            img: [
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product2.jpg",
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product2-1-582x650.jpg",
              "https://okab.pixeldima.com/shop/wp-content/uploads/sites/5/2016/04/product2-2-582x650.jpg",
            ],
            newProduct: "1",
            price: 254,
            productId: 2,
            productName: "SBIBITA KAHLA SAFRA",
            productTags: [
              "black",
              "boots",
              "Cotton",
              "glasses",
              "red",
              "shoes",
              "Yepme",
            ],
            review: "4",
            size: ["39, 40, 41, 42, 43"],
          },
          sl: 2,
        },
      ],
    },
  ];
// localStorage.setItem('products', JSON.stringify(products))


